param(
    [string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$Force,
    [switch]$AdoptExisting
)

$ErrorActionPreference = 'Stop'
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$repositoryRootPath = [System.IO.Path]::GetFullPath($RepositoryRoot)
$plansRoot = [System.IO.Path]::GetFullPath((Join-Path $repositoryRootPath 'plans'))
$repositoryGitFlowPath = Join-Path $repositoryRootPath 'docs\07-release\GIT_FLOW.md'
$generatedMarker = '<!-- GENERATED BY scripts/Generate-TaskFiles.ps1; edit phase README/TASKS sources, then regenerate. -->'
$validTaskModes = @('PLAN', 'IMPLEMENT', 'DEBUG', 'REVIEW', 'REFACTOR', 'SECURITY_REVIEW', 'MIGRATION', 'RELEASE')
$validTaskRisks = @('Low', 'Medium', 'High', 'Critical')
$validTaskStatuses = @('BACKLOG', 'READY', 'IN_PROGRESS', 'BLOCKED', 'REVIEW', 'VERIFY', 'DONE', 'CANCELLED')

if (-not (Test-Path -LiteralPath $repositoryGitFlowPath -PathType Leaf)) {
    throw "Repository Git flow not found: $repositoryGitFlowPath"
}

$repositoryGitFlow = Get-Content -LiteralPath $repositoryGitFlowPath -Raw -Encoding utf8
$gitPolicyStatus = if ($repositoryGitFlow -match '\| Status \| `(?<status>[A-Z]+)') {
    $Matches.status
}
else {
    throw 'Cannot parse repository Git flow status.'
}

function Assert-PathWithinRepository {
    param([string]$Path)

    $resolved = [System.IO.Path]::GetFullPath($Path)
    $prefix = $repositoryRootPath.TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar
    ) + [System.IO.Path]::DirectorySeparatorChar

    if (-not $resolved.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to write outside repository: $resolved"
    }
}

function Assert-GeneratedFileWriteAllowed {
    param(
        [string]$Path,
        [string]$Label
    )

    Assert-PathWithinRepository -Path $Path
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return
    }

    if (-not $Force) {
        throw "$Label already exists: $Path. Use -Force only after reviewing source and generated-file changes."
    }

    $firstLine = Get-Content -LiteralPath $Path -Encoding utf8 -TotalCount 1
    if ($firstLine -ne $generatedMarker -and -not $AdoptExisting) {
        throw "Refusing to overwrite unmanaged $Label`: $Path. Use -AdoptExisting only after confirming it is safe to replace."
    }
}

function Get-PhaseGitMetadata {
    param([string]$PhaseCode)

    switch ($PhaseCode) {
        'P00' {
            return @{
                Branch = 'phase/p00-governance'
                Base = '`main` sau khi Git repository bootstrap được phê duyệt rõ'
                Scope = 'repo'
                Gate = 'Build/CI/architecture/workflow baseline'
                Tag = 'm0-governance'
            }
        }
        'P01' {
            return @{
                Branch = 'phase/p01-security-domain'
                Base = '`main` tại tag `m0-governance`'
                Scope = 'security'
                Gate = 'Domain, policy, permission, confirmation và audit'
                Tag = 'm1-security-domain'
            }
        }
        'P02' {
            return @{
                Branch = 'phase/p02-local-assistant'
                Base = '`main` tại tag `m1-security-domain`'
                Scope = 'assistant'
                Gate = 'Offline/private-mode local assistant journey'
                Tag = 'm2-local-assistant'
            }
        }
        'P03' {
            return @{
                Branch = 'phase/p03-safe-automation'
                Base = '`main` tại tag `m2-local-assistant`'
                Scope = 'automation'
                Gate = 'Worker/browser/terminal isolation và verification'
                Tag = 'm3-safe-automation'
            }
        }
        'P04' {
            return @{
                Branch = 'phase/p04-memory-routines'
                Base = '`main` tại tag `m3-safe-automation`'
                Scope = 'memory'
                Gate = 'Local memory/delete/routine trust semantics'
                Tag = 'm4-memory-routines'
            }
        }
        'P05' {
            return @{
                Branch = 'phase/p05-cloud-multidevice'
                Base = '`main` tại tag `m4-memory-routines`'
                Scope = 'cloud'
                Gate = 'Cloud disclosure, sync, web/mobile và revoke'
                Tag = 'm5-cloud-multidevice'
            }
        }
        'P06' {
            return @{
                Branch = 'phase/p06-integrations'
                Base = '`main` tại tag `m5-cloud-multidevice`'
                Scope = 'integrations'
                Gate = 'Messaging/Home Assistant scoped integration'
                Tag = 'm6-integrations'
            }
        }
        'P07' {
            return @{
                Branch = 'phase/p07-hardening-release'
                Base = '`main` tại tag `m6-integrations`'
                Scope = 'release'
                Gate = 'Full AC/security/recovery/release checklist'
                Tag = 'v{approved-semver}'
            }
        }
        default { throw "Unknown phase code: $PhaseCode" }
    }
}

function Get-TaskBranchType {
    param(
        [string]$PhaseCode,
        [string]$Mode,
        [string]$Title
    )

    if ($Title -match '(?i)bug|fix|finding|lỗi') {
        return 'fix'
    }

    if ($Title -match '(?i)test|kiểm thử|suite|benchmark|measure|verification|verify phase|audit|rehearsal|fault|adversarial|security scan') {
        return 'test'
    }

    if ($Title -match '(?i)doc|spec|decision|roadmap|scope|matrix|freeze|git|release note|changelog|task template|threat model|chuẩn hóa|chốt ') {
        return 'docs'
    }

    if ($Title -match '(?i)solution|project reference|ci |configuration|config |analyzer|installer|verified update|update integrity|sbom|dependency|package|tooling') {
        return 'chore'
    }

    if ($Mode -eq 'PLAN') {
        return 'docs'
    }

    if ($Mode -eq 'SECURITY_REVIEW') {
        return 'test'
    }

    if ($PhaseCode -eq 'P00') {
        return 'chore'
    }

    return 'feat'
}

function ConvertTo-BranchSlug {
    param([string]$Text)

    $source = $Text.Replace('Đ', 'D').Replace('đ', 'd')
    $normalized = $source.Normalize([System.Text.NormalizationForm]::FormD)
    $builder = [System.Text.StringBuilder]::new()

    foreach ($character in $normalized.ToCharArray()) {
        $category = [System.Globalization.CharUnicodeInfo]::GetUnicodeCategory($character)
        if ($category -ne [System.Globalization.UnicodeCategory]::NonSpacingMark) {
            [void]$builder.Append($character)
        }
    }

    $ascii = $builder.ToString().Normalize([System.Text.NormalizationForm]::FormC).ToLowerInvariant()
    $slug = ([regex]::Replace($ascii, '[^a-z0-9]+', '-')).Trim('-')
    if ([string]::IsNullOrWhiteSpace($slug)) {
        $slug = 'task'
    }

    if ($slug.Length -gt 48) {
        $slug = $slug.Substring(0, 48).TrimEnd('-')
        $lastSeparator = $slug.LastIndexOf('-')
        if ($lastSeparator -ge 24) {
            $slug = $slug.Substring(0, $lastSeparator)
        }
    }

    return $slug
}

function Get-BusinessRuleSummary {
    param([string]$PhaseCode)

    switch ($PhaseCode) {
        'P00' { return '`BR-GOV-*`, `BR-SEC-*`, `BR-BAN-*` khi áp dụng.' }
        'P01' { return '`BR-GOV-*`, `BR-ID-*`, `BR-DEV-*`, `BR-AI-*`, `BR-ACT-*`, `BR-AUD-*`, `BR-SEC-*` khi áp dụng.' }
        'P02' { return '`BR-INT-*`, `BR-MODE-*`, `BR-AI-*`, `BR-ACT-*`, `BR-UI-*`, `BR-AUD-*`, `BR-OPS-*` khi áp dụng.' }
        'P03' { return '`BR-AI-*`, `BR-ACT-*`, `BR-UI-*`, `BR-TRM-*`, `BR-SEC-*`, `BR-AUD-*`, `BR-OPS-*`, `BR-BAN-*` khi áp dụng.' }
        'P04' { return '`BR-MEM-*`, `BR-RTN-*`, `BR-ACT-*`, `BR-TRM-*`, `BR-MODE-*`, `BR-AUD-*`, `BR-OPS-*` khi áp dụng.' }
        'P05' { return '`BR-ID-*`, `BR-DEV-*`, `BR-MODE-*`, `BR-ACT-*`, `BR-MEM-*`, `BR-SEC-*`, `BR-AUD-*`, `BR-OPS-*` khi áp dụng.' }
        'P06' { return '`BR-COM-*`, `BR-HA-*`, `BR-SEC-*`, `BR-ACT-*`, `BR-RTN-*`, `BR-AUD-*`, `BR-OPS-*`, `BR-BAN-*` khi áp dụng.' }
        'P07' { return 'Toàn bộ `BR-*`; ưu tiên `BR-GOV-*`, `BR-ACT-*`, `BR-SEC-*`, `BR-AUD-*`, `BR-OPS-*`, `BR-BAN-*`.' }
        default { throw "Unknown phase code: $PhaseCode" }
    }
}

function Get-DependencyRuleSummary {
    param([string]$PhaseCode)

    switch ($PhaseCode) {
        'P00' { return '`DR-001`–`DR-030`, ưu tiên dependency direction, composition, secret và CI validation.' }
        'P01' { return '`DR-001`–`DR-017`, `DR-021`–`DR-030`.' }
        'P02' { return '`DR-003`, `DR-008`, `DR-015`–`DR-022`, `DR-025`–`DR-029`.' }
        'P03' { return '`DR-008`, `DR-015`–`DR-020`, `DR-022`–`DR-030`.' }
        'P04' { return '`DR-013`, `DR-021`, `DR-023`–`DR-030`.' }
        'P05' { return '`DR-006`, `DR-008`, `DR-012`–`DR-030`.' }
        'P06' { return '`DR-003`, `DR-008`, `DR-012`, `DR-015`–`DR-027`, `DR-030`.' }
        'P07' { return 'Toàn bộ `DR-001`–`DR-030`.' }
        default { throw "Unknown phase code: $PhaseCode" }
    }
}

function Get-LifecycleSummary {
    param([string]$Text)

    $mappings = [ordered]@{
        '(?i)account' = @('UserAccount', 'AssistantProfile')
        '(?i)device|pairing|rekey' = @('DeviceNode', 'DeviceSession')
        '(?i)voice|wake' = @('VoiceWakeProfile')
        '(?i)interaction|clarification|context' = @('InteractionSession', 'ClarificationRequest')
        '(?i)action plan|plan hash' = @('ActionPlan')
        '(?i)action engine|actiontask|action task|execution' = @('ActionPlan', 'ActionTask')
        '(?i)permission' = @('PermissionGrant')
        '(?i)confirmation' = @('ConfirmationRequest')
        '(?i)memory sync|tombstone|conflict' = @('MemoryRecord', 'MemorySyncJob')
        '(?i)memory' = @('MemoryRecord')
        '(?i)routine' = @('RoutineDefinition', 'RoutineRun')
        '(?i)skill|plugin' = @('SkillPackage')
        '(?i)terminal workflow|terminal runner' = @('TerminalWorkflowDefinition', 'WorkerProcess', 'ActionTask')
        '(?i)worker|process' = @('WorkerProcess')
        '(?i)integration connection|integration authorize|integration capability' = @('IntegrationConnection')
        '(?i)credential|secret|vault' = @('CredentialSecret')
        '(?i)message|recipient|delivery' = @('OutboundMessage')
        '(?i)home assistant|ha entity|ha read|ha low|ha policy' = @('IntegrationConnection', 'HomeAssistantEntityBinding')
        '(?i)provider|routing' = @('AiProviderConfiguration')
        '(?i)local model' = @('LocalModelRuntime')
        '(?i)browser|tab|ui target|extension' = @('UiTargetSnapshot')
        '(?i)audit' = @('AuditRecord')
        '(?i)safe mode|security incident|threat' = @('AssistantProfile', 'SecurityIncident')
    }

    $entities = [System.Collections.Generic.List[string]]::new()
    foreach ($entry in $mappings.GetEnumerator()) {
        if ($Text -match $entry.Key) {
            foreach ($entity in $entry.Value) {
                if (-not $entities.Contains($entity)) {
                    $entities.Add($entity)
                }
            }
        }
    }

    if ($entities.Count -eq 0) {
        return 'Không thay đổi lifecycle trực tiếp. Nếu task phát sinh transition mới, phải cập nhật lifecycle/spec trước khi implement.'
    }

    return ($entities | ForEach-Object { "``$_``" }) -join ', '
}

function Get-TestPlan {
    param(
        [string]$Mode,
        [string]$Risk,
        [string]$Title
    )

    if ($Mode -eq 'PLAN') {
        return @(
            '- Review: kiểm tra decision/spec/traceability và link nội bộ.',
            '- Validation: chạy validator tài liệu hoặc cấu hình áp dụng.',
            '- Manual: xác nhận output đủ để task phụ thuộc bắt đầu mà không suy đoán.'
        )
    }

    if ($Mode -eq 'RELEASE') {
        return @(
            '- Automated: chạy gate hoặc suite được nêu trong acceptance.',
            '- Security: bắt buộc cho release evidence.',
            '- Manual: lưu artifact/report và kết quả rollback/recovery khi áp dụng.'
        )
    }

    $items = [System.Collections.Generic.List[string]]::new()
    $items.Add('- Unit: kiểm tra outcome, guard và failure path của task.')

    if ($Title -match '(?i)adapter|persistence|outbox|worker|bridge|api|store|sync|send|home assistant|installer|update|integration') {
        $items.Add('- Integration/contract: kiểm tra boundary với fake, sandbox hoặc test service.')
    }

    if ($Title -match '(?i)solution|architecture|adapter|api|worker|extension|integration|persistence') {
        $items.Add('- Architecture: kiểm tra dependency/module boundary.')
    }

    if ($Risk -in @('High', 'Critical')) {
        $items.Add('- Security: kiểm tra deny path, input, permission, secret và abuse case áp dụng.')
    }

    if ($Title -match '(?i)ui|desktop|voice|wake|demo|benchmark|measure|journey|installer|release') {
        $items.Add('- Manual: lưu evidence quan sát được trên target/reference environment.')
    }

    return $items.ToArray()
}

if (-not (Test-Path -LiteralPath $plansRoot -PathType Container)) {
    throw "Plans directory not found: $plansRoot"
}

$phaseDirectories = Get-ChildItem -LiteralPath $plansRoot -Directory -Filter 'phase-*' | Sort-Object Name
$generatedCount = 0

foreach ($phaseDirectory in $phaseDirectories) {
    $phaseReadmePath = Join-Path $phaseDirectory.FullName 'README.md'
    $phaseBacklogPath = Join-Path $phaseDirectory.FullName 'TASKS.md'
    $taskDirectoryPath = Join-Path $phaseDirectory.FullName 'tasks'

    Assert-PathWithinRepository -Path $phaseReadmePath
    Assert-PathWithinRepository -Path $phaseBacklogPath
    Assert-PathWithinRepository -Path $taskDirectoryPath

    $phaseReadmeLines = Get-Content -LiteralPath $phaseReadmePath -Encoding utf8
    $phaseBacklogLines = Get-Content -LiteralPath $phaseBacklogPath -Encoding utf8
    $phaseTitle = ($phaseReadmeLines | Where-Object { $_ -match '^# ' } | Select-Object -First 1) -replace '^# ', ''
    $phaseCode = if ($phaseTitle -match '^(P\d{2})') { $Matches[1] } else { throw "Cannot parse phase code: $phaseTitle" }
    $phaseGit = Get-PhaseGitMetadata -PhaseCode $phaseCode

    $readmeTasks = @{}
    foreach ($line in $phaseReadmeLines) {
        if ($line -match '^\| (?<id>P\d{2}-T\d{2}) \| (?<mode>[A-Z_]+) \| (?<risk>Low|Medium|High|Critical) \| (?<priority>[^|]+) \| (?<title>[^|]+) \| (?<depends>[^|]+) \| (?<evidence>[^|]+) \|$') {
            if ($readmeTasks.ContainsKey($Matches.id)) {
                throw "Duplicate task metadata in $($phaseDirectory.Name): $($Matches.id)"
            }
            if ($validTaskModes -notcontains $Matches.mode) {
                throw "Invalid task mode for $($Matches.id): $($Matches.mode)"
            }
            if ($validTaskRisks -notcontains $Matches.risk) {
                throw "Invalid task risk for $($Matches.id): $($Matches.risk)"
            }
            $readmeTasks[$Matches.id] = [PSCustomObject]@{
                Mode = $Matches.mode.Trim()
                Risk = $Matches.risk.Trim()
                Priority = $Matches.priority.Trim()
                Title = $Matches.title.Trim()
            }
        }
    }

    $taskRows = [System.Collections.Generic.List[object]]::new()
    $backlogTaskIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($line in $phaseBacklogLines) {
        if ($line -match '^\| (?:\[(?<linkedId>P\d{2}-T\d{2})\]\([^)]+\)|(?<plainId>P\d{2}-T\d{2})) \| (?<size>[^|]+) \| (?<status>[A-Z_]+) \| (?<outcome>[^|]+) \| (?<depends>[^|]+) \| (?<evidence>[^|]+) \|$') {
            $taskId = if ($Matches.linkedId) { $Matches.linkedId } else { $Matches.plainId }
            if (-not $backlogTaskIds.Add($taskId)) {
                throw "Duplicate task backlog row in $($phaseDirectory.Name): $taskId"
            }
            if (-not $readmeTasks.ContainsKey($taskId)) {
                throw "Task $taskId exists in TASKS.md but not README.md"
            }
            if ($validTaskStatuses -notcontains $Matches.status.Trim()) {
                throw "Invalid task status for $taskId`: $($Matches.status.Trim())"
            }

            $taskRows.Add([PSCustomObject]@{
                Id = $taskId
                Size = $Matches.size.Trim()
                Status = $Matches.status.Trim()
                Outcome = $Matches.outcome.Trim()
                Depends = $Matches.depends.Trim()
                Evidence = $Matches.evidence.Trim()
                Mode = $readmeTasks[$taskId].Mode
                Risk = $readmeTasks[$taskId].Risk
                Priority = $readmeTasks[$taskId].Priority
                Title = $readmeTasks[$taskId].Title
            })
        }
    }

    if ($taskRows.Count -ne $readmeTasks.Count) {
        throw "Task count mismatch in $($phaseDirectory.Name): README=$($readmeTasks.Count), TASKS=$($taskRows.Count)"
    }

    if (Test-Path -LiteralPath $taskDirectoryPath) {
        $existingTaskFiles = Get-ChildItem -LiteralPath $taskDirectoryPath -File -Filter 'P??-T??.md' -ErrorAction SilentlyContinue
        $expectedTaskFileNames = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
        foreach ($taskRow in $taskRows) {
            [void]$expectedTaskFileNames.Add("$($taskRow.Id).md")
        }
        $staleTaskFiles = @($existingTaskFiles | Where-Object { -not $expectedTaskFileNames.Contains($_.Name) })
        if ($staleTaskFiles.Count -gt 0) {
            $stalePaths = ($staleTaskFiles.FullName -join ', ')
            throw "Stale generated task file(s) require explicit archival/removal; no file was deleted: $stalePaths"
        }
    }
    else {
        New-Item -ItemType Directory -Path $taskDirectoryPath | Out-Null
    }

    $indexRows = [System.Collections.Generic.List[string]]::new()
    foreach ($task in $taskRows) {
        $mode = $task.Mode
        $risk = $task.Risk
        $businessRules = Get-BusinessRuleSummary -PhaseCode $phaseCode
        $dependencyRules = Get-DependencyRuleSummary -PhaseCode $phaseCode
        $lifecycle = Get-LifecycleSummary -Text "$($task.Title) $($task.Outcome)"
        $testPlan = Get-TestPlan -Mode $mode -Risk $risk -Title $task.Title
        $branchType = Get-TaskBranchType -PhaseCode $phaseCode -Mode $mode -Title $task.Title
        $branchSlug = ConvertTo-BranchSlug -Text $task.Title
        $taskBranch = "$branchType/$($task.Id.ToLowerInvariant())-$branchSlug"
        $taskFilePath = Join-Path $taskDirectoryPath "$($task.Id).md"

        Assert-GeneratedFileWriteAllowed -Path $taskFilePath -Label "task file $($task.Id)"

        $taskContent = [System.Collections.Generic.List[string]]::new()
        $taskContent.Add($generatedMarker)
        $taskContent.Add("# $($task.Id) — $($task.Title)")
        $taskContent.Add('')
        $taskContent.Add('## Task contract')
        $taskContent.Add('')
        $taskContent.Add('| Thuộc tính | Giá trị |')
        $taskContent.Add('|---|---|')
        $taskContent.Add("| Task ID | ``$($task.Id)`` |")
        $taskContent.Add("| Phase | $phaseTitle |")
        $taskContent.Add("| Mode | ``$mode`` |")
        $taskContent.Add("| Priority | ``$($task.Priority)`` |")
        $taskContent.Add("| Status | ``$($task.Status)`` |")
        $taskContent.Add("| Estimated size | ``$($task.Size)`` |")
        $taskContent.Add("| Risk level | ``$risk`` |")
        $taskContent.Add("| Depends on | $($task.Depends) |")
        $taskContent.Add('')
        $taskContent.Add('## Goal')
        $taskContent.Add('')
        $taskContent.Add("$($task.Outcome).")
        $taskContent.Add('')
        $taskContent.Add('## In scope')
        $taskContent.Add('')
        $taskContent.Add("- Chỉ thực hiện outcome: $($task.Outcome).")
        $taskContent.Add("- Tạo đúng evidence được yêu cầu: $($task.Evidence).")
        $taskContent.Add('- Cập nhật test và documentation trực tiếp bị ảnh hưởng bởi outcome này.')
        $taskContent.Add('')
        $taskContent.Add('## Out of scope')
        $taskContent.Add('')
        $taskContent.Add('- Mọi capability thuộc task khác hoặc phase khác.')
        $taskContent.Add('- Refactor, dependency upgrade, migration hoặc public-contract change không cần thiết cho acceptance.')
        $taskContent.Add('- Nới permission, bỏ confirmation/validation hoặc làm yếu security gate.')
        $taskContent.Add('')
        $taskContent.Add('## Source of truth')
        $taskContent.Add('')
        $taskContent.Add('- [Phase contract](../README.md)')
        $taskContent.Add('- [Phase backlog](../TASKS.md)')
        $taskContent.Add('- [Execution roadmap](../../README.md)')
        $taskContent.Add('- [Repository instructions](../../../AGENTS.md)')
        $taskContent.Add('- [Business rules](../../../docs/00-product/BUSINESS_RULES.md)')
        $taskContent.Add('- [Entity lifecycles](../../../docs/01-domain/ENTITY_LIFECYCLES.md)')
        $taskContent.Add('- [Dependency rules](../../../docs/02-architecture/DEPENDENCY_RULES.md)')
        $taskContent.Add('- [Definition of Done](../../../docs/05-quality/DEFINITION_OF_DONE.md)')
        $taskContent.Add('- [Repository Git flow](../../../docs/07-release/GIT_FLOW.md)')
        $taskContent.Add('- [Phase Git flow](../GIT_FLOW.md)')
        $taskContent.Add('')
        $taskContent.Add('## Rules and lifecycle')
        $taskContent.Add('')
        $taskContent.Add("### Business rules")
        $taskContent.Add('')
        $taskContent.Add("- $businessRules")
        $taskContent.Add('- Execution plan phải ghi Rule ID chính xác áp dụng cho thay đổi trước khi thực thi hoặc phê duyệt.')
        $taskContent.Add('')
        $taskContent.Add('### Entity lifecycle impact')
        $taskContent.Add('')
        $taskContent.Add("- $lifecycle")
        $taskContent.Add('')
        $taskContent.Add('### Dependency rules')
        $taskContent.Add('')
        $taskContent.Add("- $dependencyRules")
        $taskContent.Add('')
        $taskContent.Add('## Preconditions')
        $taskContent.Add('')
        $taskContent.Add("- Dependency đã hoàn tất hoặc có evidence hợp lệ: $($task.Depends).")
        $taskContent.Add('- Phase entry criteria vẫn còn đúng.')
        $taskContent.Add('- Không có blocker bắt buộc dừng, thay đổi xung đột chưa rõ owner, secret thật hoặc production data.')
        $taskContent.Add('- Task phải ở `READY` trước khi sửa production code.')
        $taskContent.Add('')
        $taskContent.Add('## Acceptance criteria')
        $taskContent.Add('')
        $acceptanceMarker = if ($task.Status -eq 'DONE') { 'x' } else { ' ' }
        $gateCriterion = switch ($mode) {
            'PLAN' { 'Specification, traceability, reference và document/config validators áp dụng pass hoặc N/A có lý do.' }
            'REVIEW' { 'Review scope, evidence và quality/security gates áp dụng được đánh giá.' }
            'SECURITY_REVIEW' { 'Threat, denied/abuse path và security gates áp dụng được đánh giá.' }
            'RELEASE' { 'Release, security, recovery và acceptance gates áp dụng pass.' }
            'DEBUG' { 'Regression test và test/gate lân cận áp dụng pass.' }
            default { 'Build/test/architecture/security gates áp dụng pass hoặc N/A có lý do.' }
        }
        $failureCriterion = switch ($mode) {
            'PLAN' { 'Ambiguity, invalid reference/input và stop conditions áp dụng được kiểm tra.' }
            'REVIEW' { 'Failure, unresolved finding và review limitation được ghi rõ.' }
            'SECURITY_REVIEW' { 'Abuse, replay, denied, failure và resource-exhaustion paths áp dụng được kiểm tra.' }
            'RELEASE' { 'Failure, rollback, recovery và no-go paths áp dụng được kiểm tra.' }
            'DEBUG' { 'Reproduction, failure trigger và regression path được kiểm tra.' }
            default { 'Failure, cancellation, denied và retry/idempotency paths áp dụng được kiểm tra.' }
        }
        $taskContent.Add("- [$acceptanceMarker] AC-01 — Single outcome đạt được: $($task.Outcome).")
        $taskContent.Add("- [$acceptanceMarker] AC-02 — Evidence được lưu: $($task.Evidence).")
        $taskContent.Add("- [$acceptanceMarker] AC-03 — $gateCriterion")
        $taskContent.Add("- [$acceptanceMarker] AC-04 — $failureCriterion")
        $taskContent.Add("- [$acceptanceMarker] AC-05 — Task board, session log, working memory và next action được cập nhật.")
        $taskContent.Add('')
        $taskContent.Add('## Expected evidence')
        $taskContent.Add('')
        $taskContent.Add("- $($task.Evidence).")
        $taskContent.Add('- Command/test output có PASS/FAIL thực tế.')
        $taskContent.Add('- Không có secret, PII hoặc raw sensitive payload trong log/artifact.')
        $taskContent.Add('')
        $taskContent.Add('## Execution evidence')
        $taskContent.Add('')
        if ($task.Status -eq 'DONE') {
            $taskContent.Add("- Completion evidence: $($task.Evidence).")
            $taskContent.Add("- Canonical session evidence: ``docs/04-execution/SESSION_LOG.md`` — search ``$($task.Id)``.")
        }
        else {
            $taskContent.Add("- Completion evidence: pending; task status is ``$($task.Status)``.")
            $taskContent.Add('- Ghi command/report/path thực tế vào session log trước khi chuyển `DONE`.')
        }
        $taskContent.Add('')
        $taskContent.Add('## Test plan')
        $taskContent.Add('')
        foreach ($testItem in $testPlan) {
            $taskContent.Add($testItem)
        }
        $taskContent.Add('')
        $taskContent.Add('## Git workflow')
        $taskContent.Add('')
        $taskContent.Add("- Repository Git policy status: ``$gitPolicyStatus``.")
        if ($gitPolicyStatus -ne 'ACCEPTED') {
            $taskContent.Add('- Git mapping bên dưới là draft; không tạo/apply branch workflow cho đến khi `DEC-006` được `Accepted` và repository action được cho phép.')
        }
        $taskContent.Add("- Phase branch: ``$($phaseGit.Branch)``.")
        $taskContent.Add("- Task branch: ``$taskBranch``.")
        $taskContent.Add("- Branch point: latest reviewed commit của ``$($phaseGit.Branch)``.")
        $taskContent.Add("- Pull request target: ``$($phaseGit.Branch)``.")
        $taskContent.Add("- Commit subject gợi ý: ``$branchType($($phaseGit.Scope)): $($task.Outcome.TrimEnd('.'))``.")
        $taskContent.Add("- Commit/PR body phải chứa ``Task: $($task.Id)`` và đường dẫn evidence.")
        $taskContent.Add('- Merge policy: squash task PR sau khi acceptance và gate áp dụng pass; không push trực tiếp vào phase branch hoặc `main`.')
        if ($phaseCode -eq 'P07') {
            $taskContent.Add('- Release note: chỉ target `release/{approved-semver}` khi P07-T01 đã freeze scope/version và release owner yêu cầu; còn lại giữ phase target.')
        }
        $taskContent.Add('')
        $taskContent.Add('## Risk and rollback')
        $taskContent.Add('')
        $taskContent.Add("- Risk level: ``$risk``.")
        $taskContent.Add('- Giữ thay đổi nhỏ và có thể đảo ngược; không sửa/xóa dữ liệu thật.')
        $taskContent.Add('- Nếu schema, installer hoặc dữ liệu bị ảnh hưởng, phải bổ sung forward/recovery verification trước khi bắt đầu.')
        $taskContent.Add('- Nếu gate fail, dừng task, giữ evidence và rollback riêng thay đổi thuộc task; không tắt gate.')
        $taskContent.Add('')
        $taskContent.Add('## Stop conditions')
        $taskContent.Add('')
        $taskContent.Add('- Yêu cầu mâu thuẫn phase contract, scope hoặc business/security rule.')
        $taskContent.Add('- Cần secret thật, production data, Administrator/root hoặc external paid service chưa được duyệt.')
        $taskContent.Add('- Dependency chưa hoàn tất hoặc working tree có thay đổi xung đột chưa rõ owner.')
        $taskContent.Add('- Acceptance thay đổi đáng kể hoặc cần public-contract/architecture decision ngoài scope.')
        $taskContent.Add('')
        $taskContent.Add('## Handoff')
        $taskContent.Add('')
        $taskContent.Add('- Ghi changed files và lý do.')
        $taskContent.Add('- Ghi commands cùng PASS/FAIL.')
        $taskContent.Add('- Check từng acceptance criterion.')
        $taskContent.Add('- Cập nhật `TASK_BOARD.md`, `SESSION_LOG.md`, `WORKING_MEMORY.md` và `NEXT_ACTION.md`.')
        $taskContent.Add('- Nêu phần chưa hoàn thành, risk/debt và next executable task.')

        [System.IO.File]::WriteAllText($taskFilePath, ($taskContent -join "`n") + "`n", $utf8NoBom)
        $generatedCount++
        $indexRows.Add("| [$($task.Id)]($($task.Id).md) | $($task.Title) | $($task.Size) | $($task.Priority) | $($task.Status) | $($task.Depends) |")
    }

    $taskIndexPath = Join-Path $taskDirectoryPath 'README.md'
    Assert-GeneratedFileWriteAllowed -Path $taskIndexPath -Label "task index $phaseCode"
    $taskIndexContent = @(
        $generatedMarker,
        "# $phaseCode — Individual Task Files",
        '',
        "Task specifications cho $phaseTitle. Phase scope/rules/gates vẫn thuộc [phase contract](../README.md); trạng thái backlog được quản lý tại [TASKS.md](../TASKS.md); branch/PR rules thuộc [phase Git flow](../GIT_FLOW.md).",
        '',
        '| Task | Title | Size | Priority | Status | Depends on |',
        '|---|---|---:|---|---|---|'
    ) + $indexRows + @(
        '',
        '## Usage',
        '',
        '1. Chỉ chọn task `READY` và có dependency hoàn tất.',
        '2. Đọc task file, phase contract và source-of-truth links.',
        '3. Nêu execution plan/file/test trước khi sửa.',
        '4. Cập nhật source `TASKS.md`, task board/session state, rồi chạy generator để đồng bộ task view.',
        '5. Không sửa trực tiếp generated task/index file; generator sẽ từ chối overwrite file không có generated marker.',
        ''
    )
    [System.IO.File]::WriteAllText($taskIndexPath, ($taskIndexContent -join "`n"), $utf8NoBom)

    $phaseGitFlowPath = Join-Path $phaseDirectory.FullName 'GIT_FLOW.md'
    Assert-GeneratedFileWriteAllowed -Path $phaseGitFlowPath -Label "phase Git flow $phaseCode"
    $phaseGitRows = [System.Collections.Generic.List[string]]::new()
    foreach ($task in $taskRows) {
        $mode = $task.Mode
        $branchType = Get-TaskBranchType -PhaseCode $phaseCode -Mode $mode -Title $task.Title
        $branchSlug = ConvertTo-BranchSlug -Text $task.Title
        $taskBranch = "$branchType/$($task.Id.ToLowerInvariant())-$branchSlug"
        $phaseGitRows.Add("| [$($task.Id)](tasks/$($task.Id).md) | ``$taskBranch`` | ``$($phaseGit.Branch)`` | $($task.Evidence) |")
    }

    $phaseGitFlowContent = [System.Collections.Generic.List[string]]::new()
    $phaseGitFlowContent.Add($generatedMarker)
    $phaseGitFlowContent.Add("# $phaseCode — Phase Git Flow")
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add("Git workflow thực thi cho $phaseTitle. Policy chuẩn thuộc [repository Git flow](../../docs/07-release/GIT_FLOW.md); file này không thay đổi phase scope.")
    if ($gitPolicyStatus -ne 'ACCEPTED') {
        $phaseGitFlowContent.Add('')
        $phaseGitFlowContent.Add("> Draft mapping: repository Git policy is ``$gitPolicyStatus``. Do not apply until ``DEC-006`` is accepted and Git actions are authorized.")
    }
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Phase branch contract')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('| Thuộc tính | Giá trị |')
    $phaseGitFlowContent.Add('|---|---|')
    $phaseGitFlowContent.Add("| Repository policy status | ``$gitPolicyStatus`` |")
    $phaseGitFlowContent.Add("| Phase branch | ``$($phaseGit.Branch)`` |")
    $phaseGitFlowContent.Add("| Tạo từ | $($phaseGit.Base) |")
    $phaseGitFlowContent.Add("| Task PR target | ``$($phaseGit.Branch)`` |")
    $phaseGitFlowContent.Add('| Task merge | Squash merge sau review và evidence |')
    $phaseGitFlowContent.Add('| Phase merge | Merge commit vào `main` sau phase gate |')
    $phaseGitFlowContent.Add("| Required phase gate | $($phaseGit.Gate) |")
    $phaseGitFlowContent.Add("| Tag sau gate | ``$($phaseGit.Tag)`` |")
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Branch flow')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('```mermaid')
    $phaseGitFlowContent.Add('flowchart LR')
    $phaseGitFlowContent.Add("    M[main] --> P[$($phaseGit.Branch)]")
    $phaseGitFlowContent.Add('    P --> T[task branch]')
    $phaseGitFlowContent.Add("    T --> R[PR to $($phaseGit.Branch)]")
    $phaseGitFlowContent.Add('    R --> P')
    $phaseGitFlowContent.Add('    P --> G[Phase gate PR]')
    $phaseGitFlowContent.Add('    G --> M')
    $phaseGitFlowContent.Add('```')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Task branch map')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('| Task | Suggested branch | PR target | Required task evidence |')
    $phaseGitFlowContent.Add('|---|---|---|---|')
    foreach ($row in $phaseGitRows) {
        $phaseGitFlowContent.Add($row)
    }
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Execution rules')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add("1. Phase owner tạo ``$($phaseGit.Branch)`` từ $($phaseGit.Base) sau khi entry criteria pass.")
    $phaseGitFlowContent.Add('2. Task owner chỉ tạo suggested task branch khi task `READY` và dependency có evidence.')
    $phaseGitFlowContent.Add("3. Draft PR target ``$($phaseGit.Branch)``; PR ghi Task ID, acceptance, commands, security/architecture impact và rollback.")
    $phaseGitFlowContent.Add('4. Task PR được squash merge; task file, backlog và task board được đồng bộ trước merge.')
    $phaseGitFlowContent.Add("5. Phase owner chạy $($phaseGit.Gate), mở phase gate PR vào ``main`` và chỉ merge khi exit criteria pass.")
    $phaseGitFlowContent.Add("6. Sau merge, tạo annotated tag ``$($phaseGit.Tag)`` nếu checklist/approval áp dụng đã có.")
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Phase close evidence')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('- Must task inventory và unresolved findings.')
    $phaseGitFlowContent.Add('- Build/test/architecture/security reports áp dụng từ clean checkout.')
    $phaseGitFlowContent.Add('- Phase acceptance/demo evidence và failure/cancellation path.')
    $phaseGitFlowContent.Add('- Updated task board, session log, changelog/decision và handoff.')
    $phaseGitFlowContent.Add('- Rollback/recovery evidence khi phase có persistence, sync, installer hoặc external side effect.')
    if ($phaseCode -eq 'P07') {
        $phaseGitFlowContent.Add('')
        $phaseGitFlowContent.Add('## Release candidate')
        $phaseGitFlowContent.Add('')
        $phaseGitFlowContent.Add('- P07-T01 phải freeze scope và nhận approval cho version/channel trước khi tạo `release/{approved-semver}`.')
        $phaseGitFlowContent.Add('- Release branch chỉ nhận fix, test, docs, packaging và evidence; không nhận capability mới.')
        $phaseGitFlowContent.Add('- P07-T17 phải có signed release/rollback decision trước merge vào `main` và tạo version tag.')
    }
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('## Recovery')
    $phaseGitFlowContent.Add('')
    $phaseGitFlowContent.Add('- Sai base/target: dừng merge, tạo hoặc retarget PR đúng và kiểm tra diff.')
    $phaseGitFlowContent.Add('- Gate fail: sửa root cause hoặc tạo bug task; không tắt gate.')
    $phaseGitFlowContent.Add('- Secret xuất hiện: dừng push/merge, revoke và xử lý như security incident.')
    [System.IO.File]::WriteAllText($phaseGitFlowPath, ($phaseGitFlowContent -join "`n") + "`n", $utf8NoBom)

    if (-not ($phaseReadmeLines -match '\[Phase Git flow\]\(GIT_FLOW\.md\)')) {
        $updatedPhaseReadmeLines = [System.Collections.Generic.List[string]]::new()
        foreach ($line in $phaseReadmeLines) {
            $updatedPhaseReadmeLines.Add($line)
            if ($line -match '^Chi tiết size, trạng thái và acceptance cho từng task:') {
                $updatedPhaseReadmeLines.Add('')
                $updatedPhaseReadmeLines.Add('Branch, PR target và phase merge gate: [Phase Git flow](GIT_FLOW.md).')
            }
        }
        [System.IO.File]::WriteAllText($phaseReadmePath, ($updatedPhaseReadmeLines -join "`n") + "`n", $utf8NoBom)
    }

    $updatedBacklogLines = foreach ($line in $phaseBacklogLines) {
        if ($line -match '^\| (?<id>P\d{2}-T\d{2}) \|') {
            $taskId = $Matches.id
            $line -replace "^\| $taskId \|", "| [$taskId](tasks/$taskId.md) |"
        }
        else {
            $line
        }
    }
    [System.IO.File]::WriteAllText($phaseBacklogPath, ($updatedBacklogLines -join "`n") + "`n", $utf8NoBom)
}

"Generated task files: $generatedCount"
"Phase directories: $($phaseDirectories.Count)"
"Generated phase Git flows: $($phaseDirectories.Count)"
