param(
    [string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'
$repositoryRootPath = [System.IO.Path]::GetFullPath($RepositoryRoot)
$plansRoot = Join-Path $repositoryRootPath 'plans'
$centralGitFlowPath = Join-Path $repositoryRootPath 'docs\07-release\GIT_FLOW.md'
$errors = [System.Collections.Generic.List[string]]::new()
$taskIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$taskBranches = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$backlogTaskCount = 0
$taskGitContractCount = 0
$explicitMetadataCount = 0
$doneAcceptanceCount = 0
$generatedMarker = '<!-- GENERATED BY scripts/Generate-TaskFiles.ps1; edit phase README/TASKS sources, then regenerate. -->'
$validTaskModes = @('PLAN', 'IMPLEMENT', 'DEBUG', 'REVIEW', 'REFACTOR', 'SECURITY_REVIEW', 'MIGRATION', 'RELEASE')
$validTaskRisks = @('Low', 'Medium', 'High', 'Critical')

$phaseBranches = @{
    P00 = 'phase/p00-governance'
    P01 = 'phase/p01-security-domain'
    P02 = 'phase/p02-local-assistant'
    P03 = 'phase/p03-safe-automation'
    P04 = 'phase/p04-memory-routines'
    P05 = 'phase/p05-cloud-multidevice'
    P06 = 'phase/p06-integrations'
    P07 = 'phase/p07-hardening-release'
}

$requiredHeadings = @(
    '## Task contract',
    '## Goal',
    '## In scope',
    '## Out of scope',
    '## Source of truth',
    '## Rules and lifecycle',
    '## Preconditions',
    '## Acceptance criteria',
    '## Expected evidence',
    '## Execution evidence',
    '## Test plan',
    '## Git workflow',
    '## Risk and rollback',
    '## Stop conditions',
    '## Handoff'
)

function Add-ValidationError {
    param([string]$Message)
    $script:errors.Add($Message)
}

if (-not (Test-Path -LiteralPath $centralGitFlowPath -PathType Leaf)) {
    throw "Central Git flow not found: $centralGitFlowPath"
}

$centralGitFlow = Get-Content -LiteralPath $centralGitFlowPath -Raw -Encoding utf8
$gitPolicyStatus = if ($centralGitFlow -match '\| Status \| `(?<status>[A-Z]+)') {
    $Matches.status
}
else {
    Add-ValidationError 'Cannot parse repository Git flow status.'
    'UNKNOWN'
}
$phaseDirectories = Get-ChildItem -LiteralPath $plansRoot -Directory -Filter 'phase-*' | Sort-Object Name

if ($phaseDirectories.Count -ne $phaseBranches.Count) {
    Add-ValidationError "Phase count mismatch: expected=$($phaseBranches.Count), actual=$($phaseDirectories.Count)"
}

foreach ($phaseDirectory in $phaseDirectories) {
    $phaseReadmePath = Join-Path $phaseDirectory.FullName 'README.md'
    $phaseBacklogPath = Join-Path $phaseDirectory.FullName 'TASKS.md'
    $phaseGitFlowPath = Join-Path $phaseDirectory.FullName 'GIT_FLOW.md'
    $phaseReadmeLines = Get-Content -LiteralPath $phaseReadmePath -Encoding utf8
    $phaseTitle = $phaseReadmeLines | Where-Object { $_ -match '^# ' } | Select-Object -First 1

    if ($phaseTitle -notmatch '^# (?<code>P\d{2}) ') {
        Add-ValidationError "Cannot parse phase code: $phaseReadmePath"
        continue
    }

    $phaseCode = $Matches.code
    $expectedPhaseBranch = $phaseBranches[$phaseCode]
    if ([string]::IsNullOrWhiteSpace($expectedPhaseBranch)) {
        Add-ValidationError "No phase branch mapping for $phaseCode"
        continue
    }

    if (-not (Test-Path -LiteralPath $phaseGitFlowPath -PathType Leaf)) {
        Add-ValidationError "Missing phase Git flow: $phaseGitFlowPath"
        continue
    }

    $phaseGitFlow = Get-Content -LiteralPath $phaseGitFlowPath -Raw -Encoding utf8
    if ((Get-Content -LiteralPath $phaseGitFlowPath -Encoding utf8 -TotalCount 1) -ne $generatedMarker) {
        Add-ValidationError "$phaseCode Git flow is not marked as generated"
    }

    if (-not $phaseGitFlow.Contains("``$expectedPhaseBranch``")) {
        Add-ValidationError "$phaseCode Git flow does not contain expected phase branch: $expectedPhaseBranch"
    }

    if (-not $centralGitFlow.Contains("``$expectedPhaseBranch``")) {
        Add-ValidationError "Central Git flow does not contain $expectedPhaseBranch"
    }

    if ($phaseGitFlow -notmatch "(?m)^\| Repository policy status \| ``$([regex]::Escape($gitPolicyStatus))`` \|$") {
        Add-ValidationError "$phaseCode Git flow policy status does not match repository status $gitPolicyStatus"
    }

    $phaseTaskMetadata = @{}
    foreach ($line in $phaseReadmeLines) {
        if ($line -notmatch '^\| (?<id>P\d{2}-T\d{2}) \| (?<mode>[A-Z_]+) \| (?<risk>Low|Medium|High|Critical) \| (?<priority>[^|]+) \| (?<title>[^|]+) \| (?<depends>[^|]+) \| (?<evidence>[^|]+) \|$') {
            continue
        }

        $taskId = $Matches.id
        $mode = $Matches.mode.Trim()
        $risk = $Matches.risk.Trim()
        if ($phaseTaskMetadata.ContainsKey($taskId)) {
            Add-ValidationError "Duplicate task metadata in $phaseCode README: $taskId"
            continue
        }
        if ($validTaskModes -notcontains $mode) {
            Add-ValidationError "$taskId has invalid explicit mode: $mode"
        }
        if ($validTaskRisks -notcontains $risk) {
            Add-ValidationError "$taskId has invalid explicit risk: $risk"
        }

        $phaseTaskMetadata[$taskId] = [PSCustomObject]@{
            Mode = $mode
            Risk = $risk
        }
    }

    $backlogLines = Get-Content -LiteralPath $phaseBacklogPath -Encoding utf8
    foreach ($line in $backlogLines) {
        if ($line -notmatch '^\| \[(?<id>P\d{2}-T\d{2})\]\(tasks/(?<fileId>P\d{2}-T\d{2})\.md\) \| (?<size>[^|]+) \| (?<status>[A-Z_]+) \|') {
            continue
        }

        $taskId = $Matches.id
        $fileId = $Matches.fileId
        $status = $Matches.status.Trim()
        $backlogTaskCount++

        if ($taskId -ne $fileId) {
            Add-ValidationError "Backlog link ID mismatch: $taskId -> $fileId"
        }

        if (-not $taskIds.Add($taskId)) {
            Add-ValidationError "Duplicate task ID: $taskId"
        }

        if (-not $phaseTaskMetadata.ContainsKey($taskId)) {
            Add-ValidationError "$taskId is missing explicit Mode/Risk metadata in phase README"
            continue
        }

        $taskMetadata = $phaseTaskMetadata[$taskId]
        $explicitMetadataCount++
        $taskFilePath = Join-Path $phaseDirectory.FullName "tasks\$taskId.md"
        if (-not (Test-Path -LiteralPath $taskFilePath -PathType Leaf)) {
            Add-ValidationError "Missing task file: $taskFilePath"
            continue
        }

        $taskContent = Get-Content -LiteralPath $taskFilePath -Raw -Encoding utf8
        if ((Get-Content -LiteralPath $taskFilePath -Encoding utf8 -TotalCount 1) -ne $generatedMarker) {
            Add-ValidationError "$taskId is not marked as generated"
        }

        foreach ($heading in $requiredHeadings) {
            if (-not $taskContent.Contains($heading)) {
                Add-ValidationError "$taskId missing heading: $heading"
            }
        }

        if ($taskContent -notmatch "(?m)^\| Task ID \| ``$([regex]::Escape($taskId))`` \|$") {
            Add-ValidationError "$taskId metadata ID mismatch"
        }

        if ($taskContent -notmatch "(?m)^\| Status \| ``$([regex]::Escape($status))`` \|$") {
            Add-ValidationError "$taskId status does not match backlog status $status"
        }

        if ($taskContent -notmatch "(?m)^\| Mode \| ``$([regex]::Escape($taskMetadata.Mode))`` \|$") {
            Add-ValidationError "$taskId mode does not match phase metadata $($taskMetadata.Mode)"
        }

        if ($taskContent -notmatch "(?m)^\| Risk level \| ``$([regex]::Escape($taskMetadata.Risk))`` \|$") {
            Add-ValidationError "$taskId risk does not match phase metadata $($taskMetadata.Risk)"
        }

        if ($taskContent -notmatch "(?m)^- Repository Git policy status: ``$([regex]::Escape($gitPolicyStatus))``\.$") {
            Add-ValidationError "$taskId Git policy status does not match repository status $gitPolicyStatus"
        }

        if ($status -eq 'DONE') {
            $checkedAcceptance = [regex]::Matches($taskContent, '(?m)^- \[x\] AC-\d{2} ')
            $uncheckedAcceptance = [regex]::Matches($taskContent, '(?m)^- \[ \] AC-\d{2} ')
            if ($checkedAcceptance.Count -ne 5 -or $uncheckedAcceptance.Count -ne 0) {
                Add-ValidationError "$taskId is DONE but acceptance is not fully checked: checked=$($checkedAcceptance.Count), unchecked=$($uncheckedAcceptance.Count)"
            }
            elseif ($taskContent -match '(?m)^- Completion evidence: pending;') {
                Add-ValidationError "$taskId is DONE but execution evidence is pending"
            }
            else {
                $doneAcceptanceCount++
            }
        }

        if ($taskContent -notmatch '(?m)^- Phase branch: `(?<phase>[^`]+)`\.$') {
            Add-ValidationError "$taskId missing phase branch contract"
            continue
        }

        if ($Matches.phase -ne $expectedPhaseBranch) {
            Add-ValidationError "$taskId phase branch mismatch: $($Matches.phase)"
        }

        if ($taskContent -notmatch '(?m)^- Task branch: `(?<branch>[^`]+)`\.$') {
            Add-ValidationError "$taskId missing task branch contract"
            continue
        }

        $taskBranch = $Matches.branch
        $expectedTaskIdPart = $taskId.ToLowerInvariant()
        if ($taskBranch -notmatch "^(feat|fix|test|docs|chore)/$expectedTaskIdPart-[a-z0-9]+(?:-[a-z0-9]+)*$") {
            Add-ValidationError "$taskId invalid task branch: $taskBranch"
        }

        if (-not $taskBranches.Add($taskBranch)) {
            Add-ValidationError "Duplicate task branch: $taskBranch"
        }

        if ($taskContent -notmatch "(?m)^- Pull request target: ``$([regex]::Escape($expectedPhaseBranch))``\.$") {
            Add-ValidationError "$taskId PR target mismatch"
        }

        if (-not $taskContent.Contains('[Repository Git flow](../../../docs/07-release/GIT_FLOW.md)')) {
            Add-ValidationError "$taskId missing central Git flow link"
        }

        if (-not $taskContent.Contains('[Phase Git flow](../GIT_FLOW.md)')) {
            Add-ValidationError "$taskId missing phase Git flow link"
        }

        if (-not $phaseGitFlow.Contains("[$taskId](tasks/$taskId.md)")) {
            Add-ValidationError "$phaseCode Git flow missing task mapping for $taskId"
        }

        $taskGitContractCount++
    }

    if ($phaseTaskMetadata.Count -ne ($backlogLines | Where-Object { $_ -match '^\| \[(P\d{2}-T\d{2})\]\(tasks/' }).Count) {
        Add-ValidationError "$phaseCode explicit metadata count does not match backlog count"
    }
}

$taskFiles = Get-ChildItem -LiteralPath $plansRoot -Recurse -File -Filter 'P??-T??.md'
$taskIndexes = Get-ChildItem -LiteralPath $plansRoot -Recurse -File -Filter 'README.md' |
    Where-Object { $_.Directory.Name -eq 'tasks' }
$phaseGitFlows = Get-ChildItem -LiteralPath $plansRoot -Recurse -File -Filter 'GIT_FLOW.md'

if ($taskFiles.Count -ne $backlogTaskCount) {
    Add-ValidationError "Task file count mismatch: backlog=$backlogTaskCount, files=$($taskFiles.Count)"
}

if ($taskIndexes.Count -ne $phaseDirectories.Count) {
    Add-ValidationError "Task index count mismatch: phases=$($phaseDirectories.Count), indexes=$($taskIndexes.Count)"
}

if ($phaseGitFlows.Count -ne $phaseDirectories.Count) {
    Add-ValidationError "Phase Git flow count mismatch: phases=$($phaseDirectories.Count), flows=$($phaseGitFlows.Count)"
}

foreach ($taskIndex in $taskIndexes) {
    if ((Get-Content -LiteralPath $taskIndex.FullName -Encoding utf8 -TotalCount 1) -ne $generatedMarker) {
        Add-ValidationError "Task index is not marked as generated: $($taskIndex.FullName)"
    }
}

$markdownFiles = @(
    Get-ChildItem -LiteralPath $plansRoot -Recurse -File -Filter '*.md'
) + @(
    Get-Item -LiteralPath $centralGitFlowPath
)

foreach ($markdownFile in $markdownFiles) {
    $content = Get-Content -LiteralPath $markdownFile.FullName -Raw -Encoding utf8
    $matches = [regex]::Matches($content, '\[[^\]]+\]\((?<target>[^)]+)\)')
    foreach ($match in $matches) {
        $target = $match.Groups['target'].Value
        if ($target -match '^(https?://|mailto:|#)') {
            continue
        }

        $pathPart = ($target -split '#', 2)[0]
        if ([string]::IsNullOrWhiteSpace($pathPart)) {
            continue
        }

        $resolvedTarget = [System.IO.Path]::GetFullPath((Join-Path $markdownFile.DirectoryName $pathPart))
        if (-not (Test-Path -LiteralPath $resolvedTarget)) {
            Add-ValidationError "Broken local link in $($markdownFile.FullName): $target"
        }
    }
}

if ($errors.Count -gt 0) {
    foreach ($validationError in $errors) {
        Write-Output "ERROR: $validationError"
    }
    throw "Task/Git flow validation failed with $($errors.Count) error(s)."
}

Write-Output "PHASES=$($phaseDirectories.Count)"
Write-Output "BACKLOG_TASKS=$backlogTaskCount"
Write-Output "INDIVIDUAL_TASK_FILES=$($taskFiles.Count)"
Write-Output "TASK_GIT_CONTRACTS=$taskGitContractCount"
Write-Output "TASK_INDEXES=$($taskIndexes.Count)"
Write-Output "PHASE_GIT_FLOWS=$($phaseGitFlows.Count)"
Write-Output "EXPLICIT_MODE_RISK=$explicitMetadataCount"
Write-Output "DONE_ACCEPTANCE=$doneAcceptanceCount"
Write-Output 'GENERATED_FILE_GUARD=PASS'
Write-Output 'BRANCH_STATUS_TARGET_LINKS=PASS'
Write-Output 'ALL_LOCAL_MARKDOWN_LINKS=PASS'
Write-Output 'VALIDATION=PASS'
